const authTypes = {
  SET_AUTHORIZED: 'SET_AUTHORIZED',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_IS_LOGIN_PROXY: 'SET_IS_LOGIN_PROXY',
  SET_ORIGINAL_TOKEN: 'SET_ORIGINAL_TOKEN',
  SET_POLICY_ROLE: 'SET_POLICY_ROLE',
  SET_POLICY_PERMISSION: 'SET_POLICY_PERMISSION',
  SET_MENUS: 'SET_MENU',
};

export { authTypes };
