DROP TABLE IF EXISTS `m_medical_function`;

CREATE TABLE `m_medical_function` (
   `facility_cd` varchar(25) NOT NULL COMMENT '施設コード',
   `announce_year` varchar(4) DEFAULT NULL COMMENT '情報_年',
   `announce_month` varchar(2) DEFAULT NULL COMMENT '情報_月',
   `announce_day` varchar(2) DEFAULT NULL COMMENT '情報_日',
   `url` varchar(200) DEFAULT NULL COMMENT '案内用ホームページアドレス',
   `prescription_in_hospital_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '院内処方フラグ',
   `prescription_out_hospital_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '院外処方フラグ',
   `clinical_trial_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '治験実施フラグ',
   `facility_equipment_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '施設設備フラグ',
   `treatment_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '疾患治療フラグ',
   `specialty_outpatient_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '専門外来フラグ',
   `community_medical_cooperation_counter_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '地域医療連携体制窓口設置フラグ',
   `community_medical_cooperation_pass_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '地域医療連携体制地域連携パスフラグ',
   `hospitalization_plan_flag` tinyint(1) unsigned DEFAULT NULL COMMENT '入院計画連携体制フラグ',
   `avg_inpatient_count_general` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院一般',
   `avg_inpatient_count_cure` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院療養',
   `avg_inpatient_count_health` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院療養(医療)',
   `avg_inpatient_count_care` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院療養(介護)',
   `avg_inpatient_count_mental` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院精神',
   `avg_inpatient_count_tuberculous` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院結核',
   `avg_inpatient_count_infection` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院感染症',
   `avg_inpatient_count_all` double(10,2) DEFAULT NULL COMMENT '患者数平均_入院全体',
   `avg_inpatient_from_year` varchar(4) DEFAULT NULL COMMENT '患者数平均_入院自年',
   `avg_inpatient_from_month` varchar(2) DEFAULT NULL COMMENT '患者数平均_入院自月',
   `avg_inpatient_from_day` varchar(2) DEFAULT NULL COMMENT '患者数平均_入院自日',
   `avg_inpatient_to_year` varchar(4) DEFAULT NULL COMMENT '患者数平均_入院至年',
   `avg_inpatient_to_month` varchar(2) DEFAULT NULL COMMENT '患者数平均_入院至月',
   `avg_inpatient_to_day` varchar(2) DEFAULT NULL COMMENT '患者数平均_入院至日',
   `avg_outpatient_count` double(10,2) DEFAULT NULL COMMENT '患者数平均_外来',
   `avg_outpatient_from_year` varchar(4) DEFAULT NULL COMMENT '患者数平均_外来自年',
   `avg_outpatient_from_month` varchar(2) DEFAULT NULL COMMENT '患者数平均_外来自月',
   `avg_outpatient_from_day` varchar(2) DEFAULT NULL COMMENT '患者数平均_外来自日',
   `avg_outpatient_to_year` varchar(4) DEFAULT NULL COMMENT '患者数平均_外来至年',
   `avg_outpatient_to_month` varchar(2) DEFAULT NULL COMMENT '患者数平均_外来至月',
   `avg_outpatient_to_day` varchar(2) DEFAULT NULL COMMENT '患者数平均_外来至日',
   `avg_home_care_patient_count` double(10,2) DEFAULT NULL COMMENT '患者数平均_在宅',
   `avg_home_care_patient_from_year` varchar(4) DEFAULT NULL COMMENT '患者数平均_在宅自年',
   `avg_home_care_patient_from_month` varchar(2) DEFAULT NULL COMMENT '患者数平均_在宅自月',
   `avg_home_care_patient_from_day` varchar(2) DEFAULT NULL COMMENT '患者数平均_在宅自日',
   `avg_home_care_patient_to_year` varchar(4) DEFAULT NULL COMMENT '患者数平均_在宅至年',
   `avg_home_care_patient_to_month` varchar(2) DEFAULT NULL COMMENT '患者数平均_在宅至月',
   `avg_home_care_patient_to_day` varchar(2) DEFAULT NULL COMMENT '患者数平均_在宅至日',
   `inpatient_count_general` int(6) DEFAULT NULL COMMENT '患者延数_入院一般',
   `inpatient_count_cure` int(6) DEFAULT NULL COMMENT '患者延数_入院療養',
   `inpatient_count_health` int(6) DEFAULT NULL COMMENT '患者延数_入院療養(医療)',
   `inpatient_count_care` int(6) DEFAULT NULL COMMENT '患者延数_入院療養(介護)',
   `inpatient_count_mental` int(6) DEFAULT NULL COMMENT '患者延数_入院精神',
   `inpatient_count_tuberculous` int(6) DEFAULT NULL COMMENT '患者延数_入院結核',
   `inpatient_count_infection` int(6) DEFAULT NULL COMMENT '患者延数_入院感染症',
   `inpatient_count_all` int(6) DEFAULT NULL COMMENT '患者延数_入院全体',
   `inpatient_from_year` varchar(4) DEFAULT NULL COMMENT '患者延数_入院自年',
   `inpatient_from_month` varchar(2) DEFAULT NULL COMMENT '患者延数_入院自月',
   `inpatient_from_day` varchar(2) DEFAULT NULL COMMENT '患者延数_入院自日',
   `inpatient_to_year` varchar(4) DEFAULT NULL COMMENT '患者延数_入院至年',
   `inpatient_to_month` varchar(2) DEFAULT NULL COMMENT '患者延数_入院至月',
   `inpatient_to_day` varchar(2) DEFAULT NULL COMMENT '患者延数_入院至日',
   `outpatient_count` int(6) DEFAULT NULL COMMENT '患者延数_外来',
   `outpatient_from_year` varchar(4) DEFAULT NULL COMMENT '患者延数_外来自年',
   `outpatient_from_month` varchar(2) DEFAULT NULL COMMENT '患者延数_外来自月',
   `outpatient_from_day` varchar(2) DEFAULT NULL COMMENT '患者延数_外来自日',
   `outpatient_to_year` varchar(4) DEFAULT NULL COMMENT '患者延数_外来至年',
   `outpatient_to_month` varchar(2) DEFAULT NULL COMMENT '患者延数_外来至月',
   `outpatient_to_day` varchar(2) DEFAULT NULL COMMENT '患者延数_外来至日',
   `home_care_patient_count` int(6) DEFAULT NULL COMMENT '患者延数_在宅',
   `home_care_patient_from_year` varchar(4) DEFAULT NULL COMMENT '患者延数_在宅自年',
   `home_care_patient_from_month` varchar(2) DEFAULT NULL COMMENT '患者延数_在宅自月',
   `home_care_patient_from_day` varchar(2) DEFAULT NULL COMMENT '患者延数_在宅自日',
   `home_care_patient_to_year` varchar(4) DEFAULT NULL COMMENT '患者延数_在宅至年',
   `home_care_patient_to_month` varchar(2) DEFAULT NULL COMMENT '患者延数_在宅至月',
   `home_care_patient_to_day` varchar(2) DEFAULT NULL COMMENT '患者延数_在宅至日',
   `avg_stay_count_general` double(10,2) DEFAULT NULL COMMENT '平均在院日数_一般',
   `avg_stay_count_cure` double(10,2) DEFAULT NULL COMMENT '平均在院日数_療養',
   `avg_stay_count_health` double(10,2) DEFAULT NULL COMMENT '平均在院日数_療養(医療)',
   `avg_stay_count_care` double(10,2) DEFAULT NULL COMMENT '平均在院日数_療養(介護)',
   `avg_stay_count_mental` double(10,2) DEFAULT NULL COMMENT '平均在院日数_精神',
   `avg_stay_count_tuberculous` double(10,2) DEFAULT NULL COMMENT '平均在院日数_結核',
   `avg_stay_count_infection` double(10,2) DEFAULT NULL COMMENT '平均在院日数_感染症',
   `avg_stay_count_all` double(10,2) DEFAULT NULL COMMENT '平均在院日数_全体',
   `avg_stay_from_year` varchar(4) DEFAULT NULL COMMENT '平均在院日数_自年',
   `avg_stay_from_month` varchar(2) DEFAULT NULL COMMENT '平均在院日数_自月',
   `avg_stay_from_day` varchar(2) DEFAULT NULL COMMENT '平均在院日数_自日',
   `avg_stay_to_year` varchar(4) DEFAULT NULL COMMENT '平均在院日数_至年',
   `avg_stay_to_month` varchar(2) DEFAULT NULL COMMENT '平均在院日数_至月',
   `avg_stay_to_day` varchar(2) DEFAULT NULL COMMENT '平均在院日数_至日',
   `created_by` varchar(15) NOT NULL COMMENT '登録者コード',
   `proxy_created_by` varchar(15) DEFAULT NULL COMMENT '登録者コード（代行ログイン者）',
   `created_at` datetime NOT NULL COMMENT '登録日時',
   `updated_by` varchar(15) NOT NULL COMMENT '更新者コード',
   `proxy_updated_by` varchar(15) DEFAULT NULL COMMENT '更新者コード（代行ログイン者コード）',
   `updated_at` datetime NOT NULL COMMENT '更新日時',
   constraint `m_medical_function_PKC` PRIMARY KEY (`facility_cd`)
 ) COMMENT='医療機能基本情報:アルトマーク:都道府県医療機能情報ファイル' ENGINE=InnoDB DEFAULT  CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;