DROP TABLE IF EXISTS `t_briefing`;

CREATE TABLE `t_briefing` (
  `briefing_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '説明会ID',
  `schedule_id` bigint(20) unsigned NOT NULL COMMENT 'スケジュールID',
  `status_type` varchar(2) NOT NULL COMMENT 'ステータス区分',
  `briefing_type` varchar(2) DEFAULT NULL COMMENT '説明会区分',
  `briefing_name` varchar(100) NOT NULL COMMENT '説明会名',
  `implement_user_cd` varchar(15) NOT NULL COMMENT 'ユーザコード（実施者）',
  `target_org_cd` varchar(20) NOT NULL COMMENT '対象組織コード',
  `facility_cd` varchar(25) DEFAULT NULL COMMENT '施設コード',
  `medical_subjects_group_cd` varchar(3) DEFAULT NULL COMMENT '診療科目分類コード',
  `place` varchar(255) DEFAULT NULL COMMENT '場所',
  `content` text DEFAULT NULL COMMENT '内容詳細',
  `disposal_technique` varchar(2) DEFAULT NULL COMMENT '弁当処分方法',
  `reason` text DEFAULT NULL COMMENT '差異理由および今後の対策',
  `note` text DEFAULT NULL COMMENT '特記事項',
  `implement_user_name` varchar(50) NOT NULL COMMENT 'ユーザ名（実施者当時）',
  `implement_user_post` varchar(2) DEFAULT NULL COMMENT 'ユーザ役職区分（実施者当時）',
  `implement_user_post_name` varchar(100) DEFAULT NULL COMMENT 'ユーザ役職名（実施者当時）',
  `implement_user_org_cd` varchar(20) NOT NULL COMMENT '組織コード（実施者当時）',
  `implement_user_org_label` varchar(30) NOT NULL COMMENT '組織ラベル（実施者当時）',
  `target_org_label` varchar(30) NOT NULL COMMENT '対象組織ラベル（当時）',
  `facility_short_name` varchar(50) DEFAULT NULL COMMENT '施設略名（当時）',
  `medical_subjects_group_name` varchar(20) DEFAULT NULL COMMENT '診療科目分類名（当時）',
  `result_only_flag` tinyint(1) unsigned NOT NULL COMMENT '結果のみフラグ',
  `remand_flag` tinyint(1) unsigned NOT NULL COMMENT '差戻しフラグ',
  `created_by` varchar(15) NOT NULL COMMENT '登録者コード',
  `proxy_created_by` varchar(15) DEFAULT NULL COMMENT '登録者コード（代行ログイン者）',
  `created_at` datetime NOT NULL COMMENT '登録日時',
  `updated_by` varchar(15) NOT NULL COMMENT '更新者コード',
  `proxy_updated_by` varchar(15) DEFAULT NULL COMMENT '更新者コード（代行ログイン者コード）',
  `updated_at` datetime NOT NULL COMMENT '更新日時',
  constraint `t_briefing_PKC` PRIMARY KEY (`briefing_id`)
) COMMENT='説明会' ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;