DROP TABLE IF EXISTS `t_knowledge`;

CREATE TABLE `t_knowledge` (
   `knowledge_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ナレッジID',
   `title` varchar(100) NOT NULL COMMENT 'タイトル',
   `knowledge_category_cd` varchar(3) NOT NULL COMMENT 'カテゴリコード',
   `knowledge_status_type` varchar(2) NOT NULL COMMENT 'ステータス区分:10:作成中、20:提出済、30:承認済、40:差し戻し中、50:公開、90:不採用',
   `product_cd` varchar(10) DEFAULT NULL COMMENT '品目コード（当時）',
   `product_name` varchar(30) DEFAULT NULL COMMENT '品目名（当時）',
   `facility_cd` varchar(25) NOT NULL COMMENT '施設コード（当時）',
   `facility_short_name` varchar(50) DEFAULT NULL COMMENT '施設略名（当時）',
   `person_cd` varchar(15) DEFAULT NULL COMMENT '個人コード（当時）',
   `person_name` varchar(50) DEFAULT NULL COMMENT '個人名（当時）',
   `department_cd` varchar(4) DEFAULT NULL COMMENT '所属部科コード（当時）',
   `department_name` varchar(100) DEFAULT NULL COMMENT '所属部科名（当時）',
   `display_position_cd` varchar(3) DEFAULT NULL COMMENT '表示役職コード（当時）',
   `display_position_name` varchar(25) DEFAULT NULL COMMENT '表示役職名（当時）',
   `medical_subjects_group_cd` varchar(3) DEFAULT NULL COMMENT '診療科目分類コード',
   `medical_subjects_group_name` varchar(20) DEFAULT NULL COMMENT '診療科目分類名（当時）',
   `facility_type_group_cd` varchar(3) DEFAULT NULL COMMENT '施設区分分類コード（当時）',
   `facility_type_group_name` varchar(20) DEFAULT NULL COMMENT '施設区分分類名（当時）',
   `contents` text NOT NULL COMMENT '内容',
   `submit_comment` text DEFAULT NULL COMMENT '提出者コメント',
   `active_point_cd` int(11) DEFAULT NULL COMMENT '活用度ポイントコード',
   `create_user_cd` varchar(15) NOT NULL COMMENT 'ユーザコード（作成者）',
   `create_datetime` datetime NOT NULL COMMENT '作成日時',
   `last_update_datetime` datetime NOT NULL COMMENT '最終更新日時',
   `first_approval_datetime` datetime DEFAULT NULL COMMENT '初回承認日時:最初に承認された日時',
   `first_release_datetime` datetime DEFAULT NULL COMMENT '初回公開日時:最初に公開された日時',
   `release_datetime` datetime DEFAULT NULL COMMENT '公開日時',
   `release_flag` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '公開済みフラグ:1:１度でも公開されたことがある',
   `anonymous_flag` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '匿名フラグ',
   `created_by` varchar(15) NOT NULL COMMENT '登録者コード',
   `proxy_created_by` varchar(15) DEFAULT NULL COMMENT '登録者コード（代行ログイン者）',
   `created_at` datetime NOT NULL COMMENT '登録日時',
   `updated_by` varchar(15) NOT NULL COMMENT '更新者コード',
   `proxy_updated_by` varchar(15) DEFAULT NULL COMMENT '更新者コード（代行ログイン者コード）',
   `updated_at` datetime NOT NULL COMMENT '更新日時',
   constraint `t_knowledge_PKC` PRIMARY KEY (`knowledge_id`)
 ) COMMENT='ナレッジ:ナレッジの本体データ' ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;