DROP TABLE IF EXISTS `t_timeline`;

CREATE TABLE `t_timeline` (
   `timeline_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'タイムラインID',
   `start_datetime` datetime NOT NULL COMMENT '開始日時',
   `end_datetime` datetime NOT NULL COMMENT '終了日時',
   `channel_type` varchar(20) NOT NULL COMMENT '活動区分:event_type＋外部サービスの専用区分値',
   `channel_id` bigint(20) unsigned NOT NULL COMMENT '活動ID:call_id、briefing_id、convention_id、外部サービスkey_id',
   `channel_detail_id` bigint(20) unsigned DEFAULT NULL COMMENT '活動詳細ID:detail_id',
   `org_label` varchar(200) DEFAULT NULL COMMENT '組織ラベル（実施者）:複数存在する場合はカンマ区切り',
   `user_cd` varchar(15) DEFAULT NULL COMMENT 'ユーザコード（実施者）',
   `user_name` varchar(30) DEFAULT NULL COMMENT 'ユーザ名（実施者）',
   `user_post_type` varchar(100) DEFAULT NULL COMMENT 'ユーザ役職区分名（実施者）',
   `title` varchar(100) DEFAULT NULL COMMENT '活動タイトル:面談：なし、説明会：説明会名、講演会：講演会名、外部システム：未定',
   `facility_cd` varchar(25) NOT NULL COMMENT '施設コード',
   `facility_short_name` varchar(50) NOT NULL COMMENT '施設略名',
   `department_name` varchar(100) DEFAULT NULL COMMENT '所属部科名',
   `person_cd` varchar(15) DEFAULT NULL COMMENT '個人コード',
   `person_name` varchar(50) DEFAULT NULL COMMENT '個人名',
   `display_position_name` varchar(25) DEFAULT NULL COMMENT '表示役職名',
   `product_name` varchar(200) DEFAULT NULL COMMENT '品目名:複数存在する場合はカンマ区切り',
   `note` text DEFAULT NULL COMMENT '特記:面談・説明会・講演会の特記事項',
   `off_label_flag` tinyint(1) unsigned DEFAULT NULL COMMENT 'オフラベルありフラグ:面談専用項目',
   `content_name` varchar(50) DEFAULT NULL COMMENT '面談内容名:面談専用項目',
   `phase_name` varchar(20) DEFAULT NULL COMMENT 'フェーズ名:面談専用項目',
   `reaction_name` varchar(20) DEFAULT NULL COMMENT '反応名:面談専用項目',
   `detail_order` int(4) DEFAULT NULL COMMENT 'ディテール順:面談専用項目',
   `convention_type_name` varchar(100) DEFAULT NULL COMMENT '講演会区分名:講演会専用項目',
   `briefing_type_name` varchar(100) DEFAULT NULL COMMENT '説明会区分名:説明会専用項目',
   `briefing_facility_short_name` varchar(50) DEFAULT NULL COMMENT '説明会対象施設略名:説明会専用項目',
   `content` varchar(100) DEFAULT NULL COMMENT 'コンテンツ:外部サービス専用項目',
   `created_by` varchar(15) NOT NULL COMMENT '登録者コード',
   `proxy_created_by` varchar(15) DEFAULT NULL COMMENT '登録者コード（代行ログイン者）',
   `created_at` datetime NOT NULL COMMENT '登録日時',
   `updated_by` varchar(15) NOT NULL COMMENT '更新者コード',
   `proxy_updated_by` varchar(15) DEFAULT NULL COMMENT '更新者コード（代行ログイン者コード）',
   `updated_at` datetime NOT NULL COMMENT '更新日時',
   constraint `t_timeline_PKC` PRIMARY KEY (`timeline_id`)
 ) COMMENT='タイムライン' ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;