const routeType = {
  SET_HISTORY: 'SET_HISTORY',
  CLEAR_HISTORY: 'CLEAR_HISTORY',
  SET_HISTORY_FROMPATH: 'SET_HISTORY_FROMPATH',
  SET_HISTORY_TOPATH: 'SET_HISTORY_TOPATH',
  SET_HISTORY_SCREEN: 'SET_HISTORY_SCREEN',
  SET_HISTORY_MODAL: 'SET_HISTORY_MODAL',
  CLEAR_MODAL: 'CLEAR_MODAL',
  SET_HISTORY_PARAMS: 'SET_HISTORY_PARAMS',
  SET_HISTORY_FILTER: 'SET_HISTORY_FILTER',
  SET_LIST_HISTORY: 'SET_LIST_HISTORY',
  SET_ITEM_INDEX: 'SET_ITEM_INDEX'
};

export { routeType };
