<?php
namespace App\Policies\Permissions;

use App\Policies\PermissionInterface;

class RoutePermission implements PermissionInterface
{
    public $groupName = 'route';
    public $memo = 'Route permission';


    /**
     * Using * for all permissions
     * Leave blank for none
     */
    public function permissions(): array
    {
        return [
            'R01' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S01_ScheduleInput',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R10' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S02_MessageManagement',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A02_S02_Stock',
                'A02_S03_StockManagement',
                'A03_S01_JapaneseDailyReportList',
                'A03_S02_DailyReport',
                'A03_S03_NotApprovedList',
                'A01_S01_ScheduleInput',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_S01_TargetFacilityList',
                'G01_S02_TargetPersonalizationInPlace',
                'G01_S03_TargetFacilityPersonalSetting',
                'G01_S04_TargetFacilityIndividualSelectionPeriodSettings',
                'G01_P01_TargetFacilityPersonalListOutput',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R20' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R31' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P01_AttendeeListOutput',
                'C01_S05_AttendantCollectiveRegistration',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R30' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P01_AttendeeListOutput',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'E01_S03_PostedUserManagement',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R40' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S03_Resignation',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R50' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'E01_S03_QaInput',
                'E01_S03_PostedUserManagement',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R60' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R70' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S02_MessageManagement',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'E01_S03_PostedUserManagement',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R80' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z02_S01_Home',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'I01_S01_UserManagement',
                'I01_S02_PermissionSetting',
                'I01_S03_ApplicationPeriodConfirmation',
                'I02_S01_PasswordReissue',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'E01_S03_PostedUserManagement',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'R90' => [
                'Z01_S01_Login',
                'Z01_S01_B_FirstLoginChangePassword',
                'Z01_S03_ProxyUserSelection',
                'Z02_S01_Home',
                'Z02_S02_MessageManagement',
                'Z02_S03_UserNotificationManagement',
                'Z04_S01_AccountSettings',
                'Z04_B01_LoadPointAggregation',
                'Z05_S01_Organization',
                'Z05_S02_AreaSelection',
                'Z05_S03_FacilitySelection',
                'Z05_S04_FacilityCustomerSelection',
                'Z05_S05_ChoiceOfMaterials',
                'Z05_S06_MaterialSelection',
                'Z05_S07_OrganizationSelectionMasterManagementRequired',
                'Z03_S01_SelectFacilitySetting',
                'Z03_S02_SelectFacilityPersonalSetting',
                'Z03_S03_SelectItemSettings',
                'Z03_S03_ConsultationContentSetting',
                'Z03_S04_SelectListCopy',
                'A02_S02_Stock',
                'A02_S03_StockManagement',
                'A03_S01_JapaneseDailyReportList',
                'A03_S02_DailyReport',
                'A03_S03_NotApprovedList',
                'I01_S01_UserManagement',
                'I01_S02_PermissionSetting',
                'I01_S03_ApplicationPeriodConfirmation',
                'I02_S01_PasswordReissue',
                'A01_S01_ScheduleInput',
                'A01_S02_Calendar',
                'A01_S03_InterviewDetails',
                'A01_S04_InterviewDetailedInput',
                'A02_B01_TransactionPastDataRemove',
                'A02_B02_ActivitySummaryUpdate',
                'H01_S01_FacilitySearch',
                'H01_S02_FacilityDetailsBasicInformation',
                'H01_S03_FacilityDetailsWorkingIndividual',
                'H01_S04_FacilityDetailsNotes',
                'H01_S05_FacilityDetailsTimeline',
                'H02_S01_PersonalSearch',
                'H02_S02_PersonalDetailsBasicInformation',
                'H02_S03_PersonalDetailsWorkingHistory',
                'H02_S04_PersonalDetailsWorkingInformation',
                'H02_S05_PersonalDetailsNotes',
                'H02_S06_PersonalDetailsTimeline',
                'H02_S07_PersonalDetailsNetworkSearch',
                'H02_S07_TimelineGeneration',
                'B01_S01_BriefingSessionList',
                'B01_S02_BriefingSessionInput',
                'C01_S01_LectureList',
                'C01_S02_LectureInput',
                'C01_S03_AttendeeList',
                'C01_P01_AttendeeListOutput',
                'C01_S04_LectureSeriesSelection',
                'C01_S05_AttendantCollectiveRegistration',
                'C01_P02_AttendantBulkRegistrationErrorContentOutput',
                'D01_S01_ListOfMaterials',
                'D01_S02_MaterialDetails',
                'D01_S03_Resignation',
                'D01_S04_CustomMaterialList',
                'D01_S05_CustomMaterialCreation',
                'D01_S06_MaterialEvaluationInput',
                'D01_S07_MaterialViewer',
                'D01_B01_OriginalMaterialUsageMapping',
                'E01_S01_QaList',
                'E01_S02_QaDetails',
                'E01_S03_QaInput',
                'E01_S03_PostedUserManagement',
                'F01_S01_KnowledgeList',
                'F01_S02_KnowledgeDetails',
                'F01_S03_KnowledgeInput',
                'F01_S04_TimelineSelection',
                'F01_S05_PreviousKnowledgeList',
                'G01_S01_TargetFacilityList',
                'G01_S02_TargetPersonalizationInPlace',
                'G01_S03_TargetFacilityPersonalSetting',
                'G01_S04_TargetFacilityIndividualSelectionPeriodSettings',
                'G01_P01_TargetFacilityPersonalListOutput',
                'G01_B01_TargetFacilityPersonalConfirmed',
            ],
            'RDev' => [
                'Z01_S02_DeveloperLogin',
            ],
        ];
    }


    /**
     * Using * for all elements
     * Leave blank for none 
     */
    public function elements(): array
    {
        return [
            'Z01_S01_Login' => ['/auth/login'],
            'Z01_S01_B_FirstLoginChangePassword' => ['/auth/first-login'],
            'Z01_S02_DeveloperLogin' => ['auth/developer-login'],
            'Z01_S03_ProxyUserSelection' => ['/proxy-user-selection'],
            'Z02_S01_Home' => ['/home'],
            'Z02_S02_MessageManagement' => ['/message-management'],
            'Z02_S03_UserNotificationManagement' => ['/user-notification-management'],
            'Z04_S01_AccountSettings' => ['/account-settings'],
            'Z04_B01_LoadPointAggregation' => ['/load-point-aggregation'],
            'Z05_S01_Organization' => ['/organization'],
            'Z05_S02_AreaSelection' => ['/area-selection'],
            'Z05_S03_FacilitySelection' => ['/facility-selection'],
            'Z05_S04_FacilityCustomerSelection' => ['/facility-customer-selection'],
            'Z05_S05_ChoiceOfMaterials' => ['/choice-of-materials'],
            'Z05_S06_MaterialSelection' => ['/material-selection'],
            'Z05_S07_OrganizationSelectionMasterManagementRequired' => ['/organization-selection-master-management-required'],
            'Z03_S01_SelectFacilitySetting' => ['/select-facility-setting'],
            'Z03_S02_SelectFacilityPersonalSetting' => ['/select-facility-personal-setting'],
            'Z03_S03_SelectItemSettings' => ['/select-item-settings'],
            'Z03_S03_ConsultationContentSetting' => ['/consultation-content-setting'],
            'Z03_S04_SelectListCopy' => ['/select-list-copy'],
            'A02_S02_Stock' => ['/stock'],
            'A02_S03_StockManagement' => ['/stock-management'],
            'A03_S01_JapaneseDailyReportList' => ['/japanese-daily-report-list'],
            'A03_S02_DailyReport' => ['/daily-report'],
            'A03_S03_NotApprovedList' => ['/not-approved-list'],
            'I01_S01_UserManagement' => ['/user-management'],
            'I01_S02_PermissionSetting' => ['/permission-setting'],
            'I01_S03_ApplicationPeriodConfirmation' => ['/application-period-confirmation'],
            'I02_S01_PasswordReissue' => ['/password-reissue'],
            'A01_S01_ScheduleInput' => ['/schedule-input'],
            'A01_S02_Calendar' => ['/calendar'],
            'A01_S03_InterviewDetails' => ['/interview-details'],
            'A01_S04_InterviewDetailedInput' => ['/interview-detailed-input'],
            'A02_B01_TransactionPastDataRemove' => ['/transaction-past-data-remove'],
            'A02_B02_ActivitySummaryUpdate' => ['/activity-summary-update'],
            'H01_S01_FacilitySearch' => ['/facility-search'],
            'H01_S02_FacilityDetailsBasicInformation' => ['/facility-details-basic-information'],
            'H01_S03_FacilityDetailsWorkingIndividual' => ['/facility-details-working-individual'],
            'H01_S04_FacilityDetailsNotes' => ['/facility-details-notes'],
            'H01_S05_FacilityDetailsTimeline' => ['/facility-details-timeline'],
            'H02_S01_PersonalSearch' => ['/personal-search'],
            'H02_S02_PersonalDetailsBasicInformation' => ['/personal-details-basic-information'],
            'H02_S03_PersonalDetailsWorkingHistory' => ['/personal-details-working-history'],
            'H02_S04_PersonalDetailsWorkingInformation' => ['/personal-details-working-information'],
            'H02_S05_PersonalDetailsNotes' => ['/personal-details-notes'],
            'H02_S06_PersonalDetailsTimeline' => ['/personal-details-timeline'],
            'H02_S07_PersonalDetailsNetworkSearch' => ['/personal-details-network-search'],
            'H02_S07_TimelineGeneration' => ['/timeline-generation'],
            'B01_S01_BriefingSessionList' => ['/briefing-session-list'],
            'B01_S02_BriefingSessionInput' => ['/briefing-session-input'],
            'C01_S01_LectureList' => ['/lecture-list'],
            'C01_S02_LectureInput' => ['/lecture-input'],
            'C01_S03_AttendeeList' => ['/attendee-list'],
            'C01_P01_AttendeeListOutput' => ['/attendee-list-output'],
            'C01_S04_LectureSeriesSelection' => ['/lecture-series-selection'],
            'C01_S05_AttendantCollectiveRegistration' => ['/attendant-collective-registration'],
            'C01_P02_AttendantBulkRegistrationErrorContentOutput' => ['/attendant-bulk-registration-error-content-output'],
            'D01_S01_ListOfMaterials' => ['/list-of-materials'],
            'D01_S02_MaterialDetails' => ['/material-details'],
            'D01_S03_Resignation' => ['/resignation'],
            'D01_S04_CustomMaterialList' => ['/custom-material-list'],
            'D01_S05_CustomMaterialCreation' => ['/custom-material-creation'],
            'D01_S06_MaterialEvaluationInput' => ['/material-evaluation-input'],
            'D01_S07_MaterialViewer' => ['/material-viewer'],
            'D01_B01_OriginalMaterialUsageMapping' => ['/original-material-usage-mapping'],
            'E01_S01_QaList' => ['/qa-list'],
            'E01_S02_QaDetails' => ['/qa-details'],
            'E01_S03_QaInput' => ['/qa-input'],
            'E01_S03_PostedUserManagement' => ['/posted-user-management'],
            'F01_S01_KnowledgeList' => ['/knowledge-list'],
            'F01_S02_KnowledgeDetails' => ['/knowledge-details'],
            'F01_S03_KnowledgeInput' => ['/knowledge-input'],
            'F01_S04_TimelineSelection' => ['/timeline-selection'],
            'F01_S05_PreviousKnowledgeList' => ['/previous-knowledge-list'],
            'G01_S01_TargetFacilityList' => ['/target-facility-list'],
            'G01_S02_TargetPersonalizationInPlace' => ['/target-personalization-in-place'],
            'G01_S03_TargetFacilityPersonalSetting' => ['/target-facility-personal-setting'],
            'G01_S04_TargetFacilityIndividualSelectionPeriodSettings' => ['/target-facility-individual-selection-period-settings'],
            'G01_P01_TargetFacilityPersonalListOutput' => ['/target-facility-personal-list-output'],
            'G01_B01_TargetFacilityPersonalConfirmed' => ['/target-facility-personal-confirmed'],
        ];
    }

    public function hiddenElements(): array
    {
        return [];
    }
}