<?php
//common
if (!defined('DUMMY_USER')) define('DUMMY_USER', 'DUMMY_USER');
if (!defined('HOME')) define('HOME', 'ホーム');
if (!defined('IS_USER')) define('IS_USER', 'is_user');
if (!defined('IS_DEVELOP')) define('IS_DEVELOP', 'is_develop');
if (!defined('ORIGINAL_MATERIAL')) define('ORIGINAL_MATERIAL', '原本資材');
if (!defined('CUSTOM_MATERIAL')) define('CUSTOM_MATERIAL', 'カスタム資材');
if (!defined('MATERIAL_CLASSIFICATION')) define('MATERIAL_CLASSIFICATION', '資材区分');
if (!defined('PRESENCE_OR_ABSENCE_OPTIONS')) define('PRESENCE_OR_ABSENCE_OPTIONS', '有無選択肢');
if (!defined('APPROVAL_BUSINESS_CLASSIFICATION')) define('APPROVAL_BUSINESS_CLASSIFICATION', '承認業務区分');
if (!defined('APPROVAL_HIERACHY')) define('APPROVAL_HIERACHY', '承認階層');
if (!defined('SYSTEM_NAME')) define('SYSTEM_NAME', 'システム名');
if (!defined('STOCK_STATUS')) define('STOCK_STATUS', 'ストックステータス');
if (!defined('ACTUAL_DIGESTION_AGGREGATION_HIERARCHY')) define('ACTUAL_DIGESTION_AGGREGATION_HIERARCHY', '実消化集計階層');
if (!defined('REPORT_STATUS_NAME_REMAND')) define('REPORT_STATUS_NAME_REMAND', '差戻');
if (!defined('REPORT_STATUS_NAME_APPROVED')) define('REPORT_STATUS_NAME_APPROVED', '承認済');
if (!defined('REPORT_STATUS_NAME_SUBMITTED')) define('REPORT_STATUS_NAME_SUBMITTED', '提出済');
if (!defined('REPORT_STATUS_VALUE_REMAND')) define('REPORT_STATUS_VALUE_REMAND', 3);
if (!defined('REPORT_STATUS_VALUE_APPROVED')) define('REPORT_STATUS_VALUE_APPROVED', 4);
if (!defined('REPORT_STATUS_VALUE_SUBMITTED')) define('REPORT_STATUS_VALUE_SUBMITTED', 2);
if (!defined('REPORT_STATUS_TYPE_UNSUBMITTED')) define('REPORT_STATUS_TYPE_UNSUBMITTED', 10);//未提出
if (!defined('REPORT_STATUS_TYPE_SUBMITTED')) define('REPORT_STATUS_TYPE_SUBMITTED', 20);//提出済み
if (!defined('REPORT_STATUS_TYPE_APPROVED')) define('REPORT_STATUS_TYPE_APPROVED', 30);//承認済み
if (!defined('REQUEST_TYPE_REPORTS')) define('REQUEST_TYPE_REPORTS', 10);//報告
if (!defined('REQUEST_TYPE_BRIEFING_PLAN')) define('REQUEST_TYPE_BRIEFING_PLAN', 20);//説明会計画
if (!defined('REQUEST_TYPE_BRIEFING_RESULTS')) define('REQUEST_TYPE_BRIEFING_RESULTS', 30);//説明会結果
if (!defined('REQUEST_TYPE_CONVENTION_PLAN')) define('REQUEST_TYPE_CONVENTION_PLAN', 40);//講演会計画
if (!defined('REQUEST_TYPE_CONVENTION_RESULTS')) define('REQUEST_TYPE_CONVENTION_RESULTS', 50);//講演会結果
if (!defined('REQUEST_TYPE_KNOWLEDGE')) define('REQUEST_TYPE_KNOWLEDGE', 60);//ナレッジ
if (!defined('APPROVAL_STATUS_PENDING')) define('APPROVAL_STATUS_PENDING', 0);//承認待ち
if (!defined('APPROVAL_STATUS_APPROVED')) define('APPROVAL_STATUS_APPROVED', 1);//承認済み
if (!defined('APPROVAL_STATUS_REMAND')) define('APPROVAL_STATUS_REMAND', 2);//差戻
if (!defined('JAPANESE_CALENDAR_ERA_CLASSIFICATION')) define('JAPANESE_CALENDAR_ERA_CLASSIFICATION', '元号');
if (!defined('GRADUATE_YEAR')) define('GRADUATE_YEAR', '年卒');
if (!defined('TIMELINE_CHANEL_DIVISION')) define('TIMELINE_CHANEL_DIVISION', 'チャネル');
if (!defined('SCHEDULE_DIVISION')) define('SCHEDULE_DIVISION', 'スケジュール区分');
if (!defined('SCHEDULE_DIVISION_CALL')) define('SCHEDULE_DIVISION_CALL', 10);//面談
if (!defined('SCHEDULE_DIVISION_BRIEFING')) define('SCHEDULE_DIVISION_BRIEFING', 20);//説明会
if (!defined('SCHEDULE_DIVISION_CONVENTION')) define('SCHEDULE_DIVISION_CONVENTION', 30);//講演会
if (!defined('SCHEDULE_DIVISION_IN_HOUSE_SCHEDULE')) define('SCHEDULE_DIVISION_IN_HOUSE_SCHEDULE', 40);//社内予定
if (!defined('SCHEDULE_DIVISION_PRIVATE')) define('SCHEDULE_DIVISION_PRIVATE', 50);//プライベート
if (!defined('NUMBER_OF_HOST_REGULATION_COMMENTS')) define('NUMBER_OF_HOST_REGULATION_COMMENTS', 'HOT規定コメント数');
if (!defined('HOT_SPECIFIED_NUMBER_OF_DAYS')) define('HOT_SPECIFIED_NUMBER_OF_DAYS', 'HOT規定日数');
if (!defined('MAXIMUM_NUMBER_OF_BEST_ANSWERS')) define('MAXIMUM_NUMBER_OF_BEST_ANSWERS', 'ベストアンサー上限数');
if (!defined('NEW_ARRIVAL_SPECIFIED_NUMBER_OF_DAYS')) define('NEW_ARRIVAL_SPECIFIED_NUMBER_OF_DAYS', '新着規定日数');
if (!defined('NO_AFFILIATION')) define('NO_AFFILIATION', '(所属なし)');
//c_system_parameter
if (!defined('LOG_ERROR_NOTIFICATION_DESTINATION')) define('LOG_ERROR_NOTIFICATION_DESTINATION', 'ログエラー通知先');
//t_inform
if (!defined('QUESTION_ID')) define('QUESTION_ID', 'question_id');
if (!defined('PERSON_CD')) define('PERSON_CD', 'person_cd');
if (!defined('DELETE_RATING_COMMENT_INFORM_CATEGORY')) define('DELETE_RATING_COMMENT_INFORM_CATEGORY', 170);//評価コメント削除
if (!defined('KNOWLEDGE_REQUEST_INFORM_CATEGORY')) define('KNOWLEDGE_REQUEST_INFORM_CATEGORY', 180);//要望・要求事項
if (!defined('REGISTER_A_QUESTION_INFORM_CATEGORY')) define('REGISTER_A_QUESTION_INFORM_CATEGORY', 190);
if (!defined('PERSON_DETAIL_NOTE_INFORM_CATEGORY')) define('PERSON_DETAIL_NOTE_INFORM_CATEGORY', 240);
if (!defined('DEFINITION_VALUE_10')) define('DEFINITION_VALUE_10', 10);// 説明会 bri 10
if (!defined('DEFINITION_VALUE_20')) define('DEFINITION_VALUE_20', 20);// 講演会 con 20
if (!defined('DEFINITION_VALUE_30')) define('DEFINITION_VALUE_30', 30);// ターゲット tar 30
if (!defined('CONVENTION_STATUS')) define('CONVENTION_STATUS', '講演会ステータス');
if (!defined('ROLE_CLASSIFICATION')) define('ROLE_CLASSIFICATION', '役割区分');
if (!defined('DEFINITION_NAME_STOCK_SOURCE_CLASSIFICATION')) define('DEFINITION_NAME_STOCK_SOURCE_CLASSIFICATION', 'ストック元区分');
if (!defined('STATUS_CONFIRMATION_CATEGORY_ATTENDANCE_SELECTION_ITEM')) define('STATUS_CONFIRMATION_CATEGORY_ATTENDANCE_SELECTION_ITEM', '状況確認区分_出欠選択項目');
if (!defined('PARAMETER_NAME_CONVENTION')) define('PARAMETER_NAME_CONVENTION', '講演会');
if (!defined('PARAMETER_KEY_CONVENTION')) define('PARAMETER_KEY_CONVENTION', '講演会フォロー期間');
if (!defined('INPUT_DEADLINE_CONVENTION')) define('INPUT_DEADLINE_CONVENTION', '入力期限');
if (!defined('ACCOMPANYING_USER_INFORM_CATEGORY')) define('ACCOMPANYING_USER_INFORM_CATEGORY', 260);
if (!defined('PARAMETER_KEYS_LATEST_PERIOD_DAYS')) define('PARAMETER_KEYS_LATEST_PERIOD_DAYS', '最新期間日数');
if (!defined('PARAMETER_KEYS_NUMBER_OF_DAYS_WITH_RENEWAL')) define('PARAMETER_KEYS_NUMBER_OF_DAYS_WITH_RENEWAL', '更新有り期間日数');
if (!defined('PARAMETER_NAME_MATERIAL_MANAGEMENT')) define('PARAMETER_NAME_MATERIAL_MANAGEMENT', '資材管理');
//t_convention, t_convetion_attendee
if (!defined('UNFOLLOW')) define('UNFOLLOW', 'ー');
if (!defined('UN_LAST_TIME_INFORMATION')) define('UN_LAST_TIME_INFORMATION', 'ー');
if (!defined('LAST_TIME_INFORMATION')) define('LAST_TIME_INFORMATION', '済');
if (!defined('UN_LAST_TIME_ATTENDED')) define('UN_LAST_TIME_ATTENDED', 'ー');
if (!defined('LAST_TIME_ATTENDED')) define('LAST_TIME_ATTENDED', '出席');
if (!defined('STATUS_ITEM_PLAN_ATTENDANCE')) define('STATUS_ITEM_PLAN_ATTENDANCE', 100);//企画時出席予定
if (!defined('STATUS_ITEM_GUIDE')) define('STATUS_ITEM_GUIDE', 200);//案内
if (!defined('STATUS_ITEM_SCHEDULE_TO_ATTEND')) define('STATUS_ITEM_SCHEDULE_TO_ATTEND', 300);//出欠予定
if (!defined('STATUS_ITEM_STAY')) define('STATUS_ITEM_STAY', 400);//宿泊
if (!defined('STATUS_ITEM_PASSPORT')) define('STATUS_ITEM_PASSPORT', 500);//旅券
if (!defined('STATUS_ITEM_TICKET')) define('STATUS_ITEM_TICKET', 600);//ﾁｹｯﾄ
if (!defined('STATUS_ITEM_ATTENDED')) define('STATUS_ITEM_ATTENDED', 700);//出席
if (!defined('STATUS_ITEM_INFO_EXCHANGE')) define('STATUS_ITEM_INFO_EXCHANGE', 800);//情報交換会
if (!defined('STATUS_ITEM_CONSOLATION_PARTY')) define('STATUS_ITEM_CONSOLATION_PARTY', 900);//慰労会
//t_question
if (!defined('UTILIZATION_POINT_TARTGET_CLASSIFICATION')) define('UTILIZATION_POINT_TARTGET_CLASSIFICATION', 30);//活用度ポイント対象区分
if (!defined('UTILIZATION_POINT_TARTGET_CLASSIFICATION_TEXT')) define('UTILIZATION_POINT_TARTGET_CLASSIFICATION_TEXT', '活用度ポイント対象区分');
if (!defined('QA_QUESTION_REGISTRATION')) define('QA_QUESTION_REGISTRATION', 20);//QA_QA質問登録
if (!defined('QUESTION_ACTIVE_POINT_MESSAGE_REGISTER')) define('QUESTION_ACTIVE_POINT_MESSAGE_REGISTER', '質問を登録しました。');
if (!defined('QUESTION_STATUS')) define('QUESTION_STATUS', 'QAステータス');
//t_knowledge
if (!defined('KNOWLEDGE_ID')) define('KNOWLEDGE_ID', 'knowledge_id');
if (!defined('ANONYMOUS')) define('ANONYMOUS', '匿名');
if (!defined('KNOWLEDGE')) define('KNOWLEDGE', 'ナレッジ');
if (!defined('SET_TO_ANONYMOUS')) define('SET_TO_ANONYMOUS', ' ※匿名に設定されています');
if (!defined('KNOWLEDGE_STATUS')) define('KNOWLEDGE_STATUS', 'ナレッジステータス');
if (!defined('NEW_ARRIAL_PERIOD_DAYS')) define('NEW_ARRIAL_PERIOD_DAYS', '新着期間日数');
if (!defined('NUMBER_OF_DAYS_WITH_RENEWAL')) define('NUMBER_OF_DAYS_WITH_RENEWAL', '更新有り期間日数');
if (!defined('KNOWLEDGE_NICE_ACTIVE_POINT_MESSAGE_REGISTER')) define('KNOWLEDGE_NICE_ACTIVE_POINT_MESSAGE_REGISTER', 'あなたのナレッジにいいねが登録されました。');
if (!defined('KNOWLEDGE_COMMENT_ACTIVE_POINT_MESSAGE_REGISTER')) define('KNOWLEDGE_COMMENT_ACTIVE_POINT_MESSAGE_REGISTER', '公開されているナレッジにコメントを登録しました。');
if (!defined('KNOWLEDGE_LIKE_REGISTRATION')) define('KNOWLEDGE_LIKE_REGISTRATION', 22);//DB: ナレッジ_ナレッジいいね登録 Spec: ナレッジいいね
if (!defined('KNOWLEDGE_LIKE_COMMENT_REGISTRATION')) define('KNOWLEDGE_LIKE_COMMENT_REGISTRATION', 23);//DB: ナレッジ_ナレッジコメント登録 Spec: ナレッジ評価コメント
if (!defined('KNOWLEDGE_STATUS_TYPE_MAKING')) define('KNOWLEDGE_STATUS_TYPE_MAKING', 10);//作成中
if (!defined('KNOWLEDGE_STATUS_TYPE_APPROVAL_IS_BEING_CONFIRMED')) define('KNOWLEDGE_STATUS_TYPE_APPROVAL_IS_BEING_CONFIRMED', 20);//承認確認中
if (!defined('KNOWLEDGE_STATUS_TYPE_WAITING_FOR_RELEASE')) define('KNOWLEDGE_STATUS_TYPE_WAITING_FOR_RELEASE', 30);//公開待ち
if (!defined('KNOWLEDGE_STATUS_TYPE_NOW_OPEN')) define('KNOWLEDGE_STATUS_TYPE_NOW_OPEN', 40);//公開中
if (!defined('KNOWLEDGE_STATUS_TYPE_NOT_ADOPTED')) define('KNOWLEDGE_STATUS_TYPE_NOT_ADOPTED', 50);//不採用
if (!defined('KNOWLEDGE_STATUS_TYPE_PRIVATE')) define('KNOWLEDGE_STATUS_TYPE_PRIVATE', 60);//非公開
if (!defined('KNOWLEDGE_APPROVAL_APPLICATION_CLASSIFICATION')) define('KNOWLEDGE_APPROVAL_APPLICATION_CLASSIFICATION', 60);//承認申請区分
//t_schedule
if (!defined('SCHEDULE_TYPE_INTERVIEW')) define('SCHEDULE_TYPE_INTERVIEW', 10);//面談
if (!defined('SCHEDULE_TYPE_INFOMATION_SESSION')) define('SCHEDULE_TYPE_INFOMATION_SESSION', 20);//説明会
if (!defined('SCHEDULE_TYPE_CONVENTION')) define('SCHEDULE_TYPE_CONVENTION', 30);//講演会
if (!defined('SCHEDULE_TYPE_IN_HOUSE_SCHEDULE')) define('SCHEDULE_TYPE_IN_HOUSE_SCHEDULE', 40);//社内予定
if (!defined('SCHEDULE_TYPE_PRIVATE')) define('SCHEDULE_TYPE_PRIVATE', 50);//プライベート
//h_approval_user
if (!defined('ROWS_OF_PAGE')) define('ROWS_OF_PAGE', 10);
//t_stock
if (!defined('STOCK_STATUS_UNPLANNED')) define('STOCK_STATUS_UNPLANNED', 10);//未計画
if (!defined('STOCK_STATUS_PLANNED')) define('STOCK_STATUS_PLANNED', 20);//計画済
//t_briefing
if (!defined('BRIEFING_STATUS_ENTERING_A_PLAN')) define('BRIEFING_STATUS_ENTERING_A_PLAN', 10);//計画入力中
if (!defined('BRIEFING_STATUS_WAITING_FOR_PLAN_APPROVAL')) define('BRIEFING_STATUS_WAITING_FOR_PLAN_APPROVAL', 20);//計画承認待ち
if (!defined('BRIEFING_STATUS_PLAN_APPROVED')) define('BRIEFING_STATUS_PLAN_APPROVED', 30);//計画承認済
if (!defined('BRIEFING_STATUS_ENTERING_RESULTS')) define('BRIEFING_STATUS_ENTERING_RESULTS', 40);//結果入力中
if (!defined('BRIEFING_STATUS_WAITING_FOR_RESULT_APPROVAL')) define('BRIEFING_STATUS_WAITING_FOR_RESULT_APPROVAL', 50);//結果承認待ち
if (!defined('BRIEFING_STATUS_RESULT_APPROVED')) define('BRIEFING_STATUS_RESULT_APPROVED', 60);//結果承認済
if (!defined('BRIEFING_STATUS_CANCEL')) define('BRIEFING_STATUS_CANCEL', 70);//中止
//t_convention
if (!defined('CONVENTION_STATUS_ENTERING_A_PLAN')) define('CONVENTION_STATUS_ENTERING_A_PLAN', 10);//計画入力中
if (!defined('CONVENTION_STATUS_WAITING_FOR_PLAN_APPROVAL')) define('CONVENTION_STATUS_WAITING_FOR_PLAN_APPROVAL', 20);//計画承認待ち
if (!defined('CONVENTION_STATUS_PLAN_APPROVED')) define('CONVENTION_STATUS_PLAN_APPROVED', 30);//計画承認済
if (!defined('CONVENTION_STATUS_ENTERING_RESULTS')) define('CONVENTION_STATUS_ENTERING_RESULTS', 40);//結果入力中
if (!defined('CONVENTION_STATUS_WAITING_FOR_RESULT_APPROVAL')) define('CONVENTION_STATUS_WAITING_FOR_RESULT_APPROVAL', 50);//結果承認待ち
if (!defined('CONVENTION_STATUS_RESULT_APPROVED')) define('CONVENTION_STATUS_RESULT_APPROVED', 60);//結果承認済
if (!defined('CONVENTION_STATUS_CANCEL')) define('CONVENTION_STATUS_CANCEL', 70);//中止
//m_person
if (!defined('PERSON_CD')) define('PERSON_CD', 'person_cd');